SELECT COUNT(*) as COUNT_DEPARTMENTS FROM sample_user.DEPARTMENTS;
SELECT COUNT(*) as COUNT_EMPLOYEES FROM sample_user.EMPLOYEES;
SELECT COUNT(*) as COUNT_PROJECTS FROM sample_user.PROJECTS;
SELECT COUNT(*) as COUNT_PA FROM sample_user.PROJECT_ASSIGNMENTS;
EXIT;
